kind: Deployment
apiVersion: apps/v1
metadata:
  name: zk-deployment-1
spec:
  selector:
    matchLabels:
      app: zk-1
  replicas: 1
  template:
    metadata:
      labels:
        app: zk-1
    spec:
      containers:
      - name: zk1
        image: bitnami/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zk1