version: '3'

services:

  rabbitmq1:
    image: rabbitmq:3.8.5-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    networks: 
      - rabbit-net
    container_name: rmq1

  rabbitmq2:
    image: rabbitmq:3.8.5-management
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    networks: 
      - rabbit-net
    container_name: rmq2

  rabbitmq3:
    image: rabbitmq:3.8.5-management
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    networks: 
      - rabbit-net
    container_name: rmq3
    
  haproxy:
    image: haproxy:1.7
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    networks: 
      - rabbit-net
    ports:
      - 15672:15672
      - 5672:5672
    container_name: proxy

networks: 
  rabbit-net:
    external: true